const BINS=[{id:'azul',name:'Papel',ptColor:'AZUL',color:'var(--azul)',dark:'var(--azul-d)'},{id:'vermelho',name:'Plástico',ptColor:'VERMELHA',color:'var(--vermelho)',dark:'var(--vermelho-d)'},{id:'verde',name:'Vidro',ptColor:'VERDE',color:'var(--verde)',dark:'var(--verde-d)'},{id:'amarelo',name:'Metal',ptColor:'AMARELA',color:'var(--amarelo)',dark:'var(--amarelo-d)'},{id:'marrom',name:'Orgânico',ptColor:'MARROM',color:'var(--marrom)',dark:'var(--marrom-d)'}];
const ITEMS=[{name:'Bola de papel',correct:'azul',svg:'📄'},{name:'Garrafa PET',correct:'vermelho',svg:'🧴'},{name:'Pote de vidro',correct:'verde',svg:'🫙'},{name:'Lata',correct:'amarelo',svg:'🥫'},{name:'Casca de banana',correct:'marrom',svg:'🍌'}];
const CHALLENGES=[{id:'first_hit',label:'Acertar 1 item',goal:1,reward:50},{id:'hot_streak',label:'Sequência de 5',goal:5,reward:120},{id:'collector',label:'500 pontos',goal:500,reward:250}];
const $=id=>document.getElementById(id); const state={score:0,streak:0,best:0,lives:3,level:1,xp:0,rewardCoins:0,checkpoint:0,queue:[],current:null,dragging:false,challengeProgress:{},challengeDone:{}};
function renderBins(){const box=$('bins');box.innerHTML='';BINS.forEach(b=>{const el=document.createElement('div');el.className='bin';el.dataset.id=b.id;el.innerHTML=`<div style="background:${b.color};border:3px solid #2b2118;border-radius:8px;height:90px"></div><div>${b.name}</div>`;box.appendChild(el);});}
function shuffleQueue(){state.queue=[...ITEMS].sort(()=>Math.random()-0.5)}
function nextItem(){if(!state.queue.length)shuffleQueue();state.current=state.queue.shift();$('item').textContent=state.current.svg;$('hint').textContent=`Onde joga ${state.current.name}?`;$('itemWrap').style.left='50%';$('itemWrap').style.top='30%';}
function updateHUD(){ $('score').textContent=state.score;$('streak').textContent=state.streak;$('hearts').textContent='❤️'.repeat(state.lives)+'🖤'.repeat(3-state.lives);$('level').textContent=state.level;$('xp').textContent=state.xp;$('rewards').textContent=state.rewardCoins;$('checkpoint').textContent=state.checkpoint; renderChallenges();}
function addXP(v){state.xp+=v; const need=100+(state.level-1)*60; if(state.xp>=need){state.xp-=need;state.level+=1;state.rewardCoins+=40; toast(`Subiu para nível ${state.level}! +40 moedas`);} }
function updateChallenges(){CHALLENGES.forEach(c=>{if(state.challengeDone[c.id])return;let p=0; if(c.id==='first_hit')p=state.score>0?1:0; if(c.id==='hot_streak')p=Math.min(state.streak,c.goal); if(c.id==='collector')p=Math.min(state.score,c.goal); state.challengeProgress[c.id]=p; if(p>=c.goal){state.challengeDone[c.id]=true;state.rewardCoins+=c.reward;toast(`Desafio concluído: ${c.label} (+${c.reward} moedas)`);}})}
function renderChallenges(){const lines=CHALLENGES.map(c=>{const p=state.challengeProgress[c.id]||0;const done=state.challengeDone[c.id]?'✅':'⬜';return `<div>${done} ${c.label}: ${p}/${c.goal}</div>`;}).join('');$('challengeList').innerHTML=lines;}
function saveCheckpoint(){state.checkpoint=Math.max(state.checkpoint,state.score); localStorage.setItem('recycleCheckpoint',JSON.stringify({score:state.checkpoint,level:state.level,rewardCoins:state.rewardCoins}));}
function loadCheckpoint(){const raw=localStorage.getItem('recycleCheckpoint'); if(!raw) return; const cp=JSON.parse(raw); state.score=cp.score||0;state.level=cp.level||1;state.rewardCoins=cp.rewardCoins||0;state.checkpoint=cp.score||0;}
function toast(msg){const el=document.createElement('div');el.className='feedback';el.textContent=msg;document.getElementById('stage').appendChild(el);setTimeout(()=>el.remove(),1200);}
function handleDrop(bin){const ok=bin.dataset.id===state.current.correct; if(ok){state.streak++;const pts=10+state.streak*2;state.score+=pts;addXP(20);if(state.streak%3===0)saveCheckpoint();toast(`Acertou +${pts}`);nextItem();} else {state.streak=0;state.lives--;toast('Errou!'); if(state.lives<=0)return gameOver();} updateChallenges(); updateHUD();}
function gameOver(){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class='card'><h2>Fim de jogo</h2><p>Pontos: ${state.score}</p><button id='playAgain'>Voltar do checkpoint</button></div>`;stage.appendChild(m);$('playAgain').onclick=()=>{m.remove(); state.lives=3; state.score=state.checkpoint; updateHUD(); nextItem();};}
function dragSetup(){const wrap=$('itemWrap'); const item=$('item'); item.onmousedown=e=>{state.dragging=true;}; window.onmousemove=e=>{if(!state.dragging)return;wrap.style.left=e.clientX+'px';wrap.style.top=e.clientY+'px';}; window.onmouseup=e=>{if(!state.dragging)return;state.dragging=false; const b=[...document.querySelectorAll('.bin')].find(x=>{const r=x.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;}); if(b)handleDrop(b); else nextItem();};}
$('restart').onclick=()=>location.reload();
loadCheckpoint(); renderBins(); shuffleQueue(); nextItem(); updateChallenges(); updateHUD(); dragSetup();
